### ISSUE TITLE
Cannot read properties of undefined reading "default" error on Windows when running project locally

### ISSUE THREAD

**Issue by Vette1123** [Dhravya/cloudflare-saas-stack#15] opened 2024-07-23 19:34 UTC
I followed your steps regarding how to run the project, but i keep getting this error

![image](https://github.com/user-attachments/assets/0b5e7099-c1c2-45a4-b9c5-ca56c7689335)

**Comment by Dhravya** [comment] 2024-07-23 20:18
I remember getting that once. Can you try deleting node_modules, installing dependencies again, and running the web app in `apps/web`?

`cd apps/web`
`bun run dev`

**Comment by Vette1123** [comment] 2024-07-23 20:28
![image](https://github.com/user-attachments/assets/13c8f9dd-32e6-4a35-9b90-2649344935ed)

same issue

**Comment by leestreetnet** [comment] 2024-07-23 20:29
Getting same error, tried deleting node_modules to no avail.

I believe it's from the `const usr = await auth()` line in `app/page.tsx` - I logged `usr` and it returns a `null` value.

**Comment by Dhravya** [comment] 2024-07-23 20:30
hmm, that should be fine tbh, @Vette1123 what operating system are you on?

**Comment by Vette1123** [comment] 2024-07-23 20:31
> hmm, that should be fine tbh, @Vette1123 what operating system are you on?

Windows 11

**Comment by jfortez** [comment] 2024-07-23 20:32
same

**Comment by Dhravya** [comment] 2024-07-23 20:33
maybe I'm unable to reproduce because I'm running on a Mac. 

I'm pretty sure this is a bun-related issue. can someone try using npm / pnpm ?

**Comment by Dhravya** [comment] 2024-07-23 20:34
Also, does anyone know why this is the case for windows? https://github.com/Dhravya/cloudflare-saas-stack/issues/11

**Comment by Vette1123** [comment] 2024-07-23 20:35
> Also, does anyone know why this is the case for windows? #11

I haven't got this error, i tried running the script, also manual setup, i only faced the issue mentioned here, haven't got the account id issue

but thanks your response, will try different package manager and let you know

**Comment by leestreetnet** [comment] 2024-07-23 20:38
ran `npm run dev` in both root and apps/web directory, still same issue

**Comment by Dhravya** [comment] 2024-07-23 20:40
Can you share the `apps/web/wrangler.toml` file?

**Comment by Vette1123** [comment] 2024-07-23 20:41
![image](https://github.com/user-attachments/assets/53b130f9-9b5b-4ffc-9cb2-ac53e0da7960)

**Comment by leestreetnet** [comment] 2024-07-23 20:41
name = "cloudflare-saas-starter"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-saas-stack-db"
database_id = "1bfdff07-2231-4b90-8778-b58850297ce8"

**Comment by jfortez** [comment] 2024-07-23 20:44
name = "cloudflare-saas-starter"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cf-app-db"
database_id = "a6a433d1-3b7e-40ab-a322-f14cb8566d4c"

**Comment by Vette1123** [comment] 2024-07-23 20:44
@Dhravya switched to pnpm and still same error 
![image](https://github.com/user-attachments/assets/de6b7b49-1a1f-42cf-9818-d55fbef5a1a0)

**Comment by Dhravya** [comment] 2024-07-23 20:44
@Vette1123 did you also install dependencies using pnpm?

**Comment by Vette1123** [comment] 2024-07-23 20:45
> @Vette1123 did you also install dependencies using pnpm?

yea,

**Comment by whistle-dev** [comment] 2024-07-23 22:59
![image](https://github.com/user-attachments/assets/738b906e-2cca-42c0-becf-db21b89e7f7c)

I get this straight from setup and bun run dev

**Comment by paulls597** [comment] 2024-07-25 14:50
I'm lost I don't even know what I'm looking at! I'm just on this site so I can look like I'm doing something important in front of my girlfriend.

**Comment by Dhravya** [comment] 2024-07-25 14:51
paul, tell your girlfriend that i said hi

to others: this is a bug in wrangler - fixing!

**Comment by Vette1123** [comment] 2024-07-25 17:37
![image](https://github.com/user-attachments/assets/1eb388c3-cdf2-4d22-b52f-7c21859733cb)

**Comment by ioabhishek** [comment] 2024-07-27 11:18
getting the same error 
![image](https://github.com/user-attachments/assets/bc33e521-a208-4e8a-a5c8-108511fb967c)

i tried setting up next project outside without turbo and it worked fine but when cloning the same repo inside turbo getting this issue
![image](https://github.com/user-attachments/assets/70af9e20-231c-4f53-96d1-f619dda97a12)


with turborepo its not working

**Comment by ioabhishek** [comment] 2024-07-27 11:26
> paul, tell your girlfriend that i said hi
> 
> to others: this is a bug in wrangler - fixing!

Hey did you got any fix for this

**Comment by Vette1123** [comment] 2024-07-27 11:30
> getting the same error ![image](https://private-user-images.githubusercontent.com/65117467/352717960-bc33e521-a208-4e8a-a5c8-108511fb967c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODAwMjYsIm5iZiI6MTcyMjA3OTcyNiwicGF0aCI6Ii82NTExNzQ2Ny8zNTI3MTc5NjAtYmMzM2U1MjEtYTIwOC00ZThhLWE1YzgtMTA4NTExZmI5NjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDExMjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MDU4ZDkwNmYyMzFmNTM4YWVkNzc5NmNlOGQwOTBjYjQ3NzYwMTI5OWRlNDI2ZmU0ODQ3OGIyYzhkNjRjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qginzPugESQfpfHIrArT5uBK39qI3bsmTXdpY2gIcr0)
> 
> i tried setting up next project outside without turbo and it worked fine but when cloning the same repo inside turbo getting this issue ![image](https://private-user-images.githubusercontent.com/65117467/352718028-70af9e20-231c-4f53-96d1-f619dda97a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODAwMjYsIm5iZiI6MTcyMjA3OTcyNiwicGF0aCI6Ii82NTExNzQ2Ny8zNTI3MTgwMjgtNzBhZjllMjAtMjMxYy00ZjUzLTk2ZDEtZjYxOWRkYTk3YTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDExMjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NzJiNjYyMjQxNWUyM2YyYmFmNjUwNDU0M2ZmODYxZGE3NWFjOTZlMWY5MTlkMjg5NGE3OTA4MGQ4Zjg1ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GI1SStFe8bQgT2Ocf1Iepr0dYjewrQasr9rYyO3TQLo)
> 
> with turborepo its not working

i solved default error by deletiny 

`export const runtime = 'edge'` from page.tsx file

but i was still getting prepare issue as the picture i attached above (it was something wrong with d1, cloudlfrare, wrangler), i swithced to turso and its working fine now, at least until cloudflare errors get solved for windows

**Comment by ioabhishek** [comment] 2024-07-27 11:56
but if we will remove this export const runtime = 'edge' then nextauth adapter will not work i think so

**Comment by Vette1123** [comment] 2024-07-27 12:49
> but if we will remove this export const runtime = 'edge' then nextauth adapter will not work i think so

it will, give it a try.

**Comment by ioabhishek** [comment] 2024-07-27 12:59
not able to figure it out, working fine in a plain next js app but cloning the same in turborepo is giving error

**Comment by codingforfoodllc** [comment] 2024-07-29 00:36
getting this error as well.

**Comment by jivjen** [comment] 2024-07-29 05:38
Yup same error for me as well on windows. Any possible workaround for this yet?

**Comment by jivjen** [comment] 2024-07-29 09:18
@codingforfoodllc @ioabhishek @leestreetnet @Vette1123 @paulls597 @jfortez @leestreetnet @Dhravya 
After some intense trial and error I have found a fix for this issue.
Go to app/web/package.json and make it 
`"dev": "next dev --turbo"`
And this resolves the D1 connectivity issue and the inital error.

Later I faced some error related to the auth call and stuff made inside page.tsx

> ⨯ Error: `headers` was called outside a request scope

 and that is coz next auth 5.0.0-beta.19 is not really in good terms with --turbo apparently lol (https://github.com/nextauthjs/next-auth/issues/11076)
So I specified the version like this "next-auth": "5.0.0-beta.18" instead of "next-auth": "^5.0.0-beta.18" and now everything works like a charm.
Also reminder to ditch windows asap! xD

**Comment by leestreetnet** [comment] 2024-07-29 17:20
@jivjen thanks for --turbo fix!

Hitting the `headers` error now and the `5.0.0-beta18` change didn't fix for me unfortunately. I'll spend some time testing too.

**Comment by jivjen** [comment] 2024-07-29 17:50
@leestreetnet Try deleting node_modules and package-lock.json from the directories and do a fresh install. Hopefully that should resolve it.

**Comment by leestreetnet** [comment] 2024-07-29 18:20
@jivjen this worked - appreciate you

Anyone working on Windows and running into these issues, @jivjen solution worked for me.

**Comment by Aunchers** [comment] 2024-08-05 00:34
@jivjen 
You are amazing.

**Closed** 2024-09-03 20:36 UTC
